### PR TITLE
Fix import path from `MakeNowJust/memefish` to `cloudspannerecosystem/memefish`

### LINKED ISSUE #51: Proposal: Move to Cloud Spanner Ecosystem org
As I sent a message personally before, we are thinking to commit a spanner parser/analyzer with feature completes for improving our tooling as Mercari engineering. We have contributed to spansql in google-cloud-go recently because it seems more official as a spanner parser.  But spansql is not a library for spanner parser, it is a testing library and not intended for feature completes as a Spanner parser. So we started thinking to create a feature complete parser.

This library was developed as part of an intern program in Mercari. Our engineers sometimes contributed this project for our spanner libraries after it was published. If we can, it's the best to make this library feature completes as a spanner parser and we also want to add some utilities for handling DML/DSL to this library.

To make the contributions more easily and keep the maintenance, we would like to ask:

1. Move this repository into [cloudspannerecosystem](https://github.com/cloudspannerecosystem) org.
2. Add another maintainer for this repository.

For 1, it makes more wider engineers to see this library and may increase a chance to get contributions other companies. We have communicated with Spanner team in Google and they encourage to move spanner related OSSs to this org. 

For 2, it just aims to decrease the burden for reviews. We don't want to break the current direction of this library. Now you are the only owner/reviewer of this repository. We would like to help the maintenance if you want.

This is just just a proposal. Please let me know your opinions, thanks.

### PR DESCRIPTION
**Pull request by makenowjust**
Close #51

Replaced `MakeNowJust/memefish` with `cloudspannerecosystem/memefish`. In addition, we notice the migration information to `README.md`.

At least, the test is passed on my laptop, however, I don't know that it works correctly.

### CODE REVIEW

**Comment by makenowjust** [comment]
@nktks @tyamagu2 I haven't been using Go much lately and would like you to review this PR.

**Comment by makenowjust** [comment]
Codecov was disabled because I have no idea how to use codecov and similar services under this org.

Another, the workflow to deploy to GH pages does not work for now. I will fix it in another PR.

**Comment by nktks** [comment]
I'm not sure about import path, but it seems to work in the case `go get` to new module.
```
go get github.com/cloudspannerecosystem/memefish@59e4bb21f177ae7789a7b72435b50bd77e23fd96
go: added github.com/cloudspannerecosystem/memefish v0.0.0-20230401063640-59e4bb21f177
```
```
cat go.mod
module github.com/nktks/test

go 1.18

require github.com/cloudspannerecosystem/memefish v0.0.0-20230401063640-59e4bb21f177 // indirect
```
```
package main

import (
	"fmt"
	"log"

	"github.com/cloudspannerecosystem/memefish/pkg/parser"
	"github.com/cloudspannerecosystem/memefish/pkg/token"
)

func main() {
	p := &parser.Parser{
		Lexer: &parser.Lexer{
			File: &token.File{FilePath: "", Buffer: "SELECT 1"},
		},
	}
	s, err := p.ParseStatement()
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(s.SQL())

}
```
```
go run main.go
SELECT 1
```

**Comment by nktks** [comment]
> Codecov was disabled because I have no idea how to use codecov and similar services under this org.

Maybe we need to request `cloudspannerechosystem` org admin to use Codecov.

@kazegusuri , @ansh0l  Can we use Codecov in `cloudspannerechosystem` org?

**Review by nktks — APPROVED** [review]
Anyway, This changes LGTM!

**Pull request merged**
